### ISSUE TITLE
Best way to install system libraries when using sys crates

### ISSUE THREAD

**Issue by paulRbr** [CircleCI-Public/cimg-rust#54]
Hello,

I'm trying out this `cimg-rust` container on CircleCI to build a Rust crate but I can't find a way to install system dependencies in the image.

Typically if I need to compile [`openssl-sys`](https://docs.rs/openssl/0.10.33/openssl/) I need openssl libraries and headers present in the build executor.

Is there a common way of installing extra system dependencies? Should I look at a different image?

Thanks for your help!

**Comment by BytesGuy** [comment]
Hello 👋  The base layer for this image is `circleci/cimg-base` which is itself based on Ubuntu. Therefore you can install packages you need with apt as normal. E.g., `sudo apt-get update && apt-get install libssl-dev`

If you want to speed this up, you can create a custom Docker image based on this one with the libraries already installed:

https://circleci.com/docs/2.0/custom-images/#creating-a-custom-image-manually

For further assistance with using our images, please reach out on our community forum:

https://discuss.circleci.com/c/ecosystem/circleci-images/64

Thanks!
