### ISSUE TITLE
Please add clippy to the image

### ISSUE THREAD

**Issue by btv** [CircleCI-Public/cimg-rust#55]
`rustup component add clippy`

Thank you in advance.

**Comment by BytesGuy** [comment]
Hello 👋 clippy is already installed by default in the latest `1.52.0` image:

```
circleci@26e1e7aa4169:~/project$ rustup component list | grep clippy
clippy-x86_64-unknown-linux-gnu (installed)
```

Is there a particular version you are using that does not appear to have clippy installed?

**Comment by BytesGuy** [comment]
I'm going to close this issue for now. Feel free to re-open it if this continues to be an issue!
