### ISSUE TITLE
Permission denied in /usr/local

### ISSUE THREAD

**Issue by ChrisBr** [CircleCI-Public/cimg-rust#88]
I don't have permissions to `/usr/local`

```
docker run -it cimg/rust:1.64.0
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
circleci@09b6951e963b:~/project$ mkdir /usr/local/cargo
/usr/bin/mkdir: cannot create directory ‘/usr/local/cargo’: Permission denied
```

I would expect `/usr/local` is world writable.

**Comment by felicianotech** [comment]
It is not world writable. Your command needs to be prefixed with `sudo`:

```bash
sudo mkdir /usr/local/cargo
```

**Comment by ChrisBr** [comment]
@felicianotech this is unexpected though. Your base image builds from `ubuntu:20.04` which allows to write to `/usr/local`. Why would you change it?

```
docker run -it ubuntu:20.04 bash
root@094cdd705e1c:/# mkdir /usr/local/cargo
root@094cdd705e1c:/#
```

**Comment by felicianotech** [comment]
We didn't. It's not work writable on that image either. That image uses and defaults to the root user. Our images defaults to the `circleci` user. Using `sudo` mimics that or `sudo su` to elevate to the root user.

**Comment by ChrisBr** [comment]
Yes just realised the base image uses root.
